export type DisputeStatus = 'IN REVIEW' | 'RESOLVED' | 'OPEN' | 'DENIED'

export type DisputePriority = 'Critical' | 'High' | 'Medium' | 'Low'

export type DisputeRow = {
  id: string
  customerId: string
  customerName: string
  customerInitials: string
  reason: string
  amountCents: number
  status: DisputeStatus
  priority: DisputePriority
  assigneeName: string | null
  assigneeInitials: string | null
  openedAt: string
}

/** Demo dataset; summary metrics use static totals in the page. */
export const DISPUTE_MOCK_ROWS: DisputeRow[] = [
  {
    id: 'DSP-90422',
    customerId: '429183',
    customerName: 'Sarah Mitchell',
    customerInitials: 'SM',
    reason: 'Unauthorized charge on invoice #9921',
    amountCents: 124_000,
    status: 'IN REVIEW',
    priority: 'Critical',
    assigneeName: 'James Chen',
    assigneeInitials: 'JC',
    openedAt: '2026-03-20T14:00:00Z',
  },
  {
    id: 'DSP-90418',
    customerId: '882104',
    customerName: 'Marcus Thorne',
    customerInitials: 'MT',
    reason: 'Damaged goods on arrival',
    amountCents: 450_00,
    status: 'RESOLVED',
    priority: 'Medium',
    assigneeName: 'Elena Rodriguez',
    assigneeInitials: 'ER',
    openedAt: '2026-03-18T09:30:00Z',
  },
  {
    id: 'DSP-90415',
    customerId: '102938',
    customerName: 'TechFlow Solutions',
    customerInitials: 'TS',
    reason: 'Billing discrepancy Q1 bundle',
    amountCents: 12_750_00,
    status: 'OPEN',
    priority: 'Low',
    assigneeName: null,
    assigneeInitials: null,
    openedAt: '2026-03-25T11:15:00Z',
  },
  {
    id: 'DSP-90411',
    customerId: '551209',
    customerName: 'Harper & Co.',
    customerInitials: 'HC',
    reason: 'Refund not processed after return',
    amountCents: 899_99,
    status: 'DENIED',
    priority: 'High',
    assigneeName: 'James Chen',
    assigneeInitials: 'JC',
    openedAt: '2026-03-10T08:00:00Z',
  },
  {
    id: 'DSP-90408',
    customerId: '771144',
    customerName: 'Jordan Lee',
    customerInitials: 'JL',
    reason: 'Duplicate charge same day',
    amountCents: 250_00,
    status: 'IN REVIEW',
    priority: 'High',
    assigneeName: 'Priya Nair',
    assigneeInitials: 'PN',
    openedAt: '2026-03-26T16:45:00Z',
  },
  {
    id: 'DSP-90402',
    customerId: '332881',
    customerName: 'Northwind Trading',
    customerInitials: 'NT',
    reason: 'Contract SLA breach claim',
    amountCents: 45_000_00,
    status: 'OPEN',
    priority: 'Critical',
    assigneeName: 'Elena Rodriguez',
    assigneeInitials: 'ER',
    openedAt: '2026-03-22T13:20:00Z',
  },
  {
    id: 'DSP-90398',
    customerId: '667021',
    customerName: 'Amir Hassan',
    customerInitials: 'AH',
    reason: 'Late delivery compensation',
    amountCents: 320_50,
    status: 'RESOLVED',
    priority: 'Low',
    assigneeName: 'James Chen',
    assigneeInitials: 'JC',
    openedAt: '2026-03-05T10:00:00Z',
  },
  {
    id: 'DSP-90395',
    customerId: '448812',
    customerName: 'Blue Ridge Logistics',
    customerInitials: 'BR',
    reason: 'Invoice mismatch — freight',
    amountCents: 8_420_00,
    status: 'IN REVIEW',
    priority: 'Medium',
    assigneeName: null,
    assigneeInitials: null,
    openedAt: '2026-03-27T09:00:00Z',
  },
  {
    id: 'DSP-90390',
    customerId: '229103',
    customerName: 'Lina Park',
    customerInitials: 'LP',
    reason: 'Subscription overcharge 3 months',
    amountCents: 189_00,
    status: 'RESOLVED',
    priority: 'Medium',
    assigneeName: 'Priya Nair',
    assigneeInitials: 'PN',
    openedAt: '2026-03-01T12:00:00Z',
  },
  {
    id: 'DSP-90388',
    customerId: '990441',
    customerName: 'Cobalt Retail Group',
    customerInitials: 'CR',
    reason: 'Chargeback — card not present',
    amountCents: 2_100_00,
    status: 'OPEN',
    priority: 'High',
    assigneeName: 'Elena Rodriguez',
    assigneeInitials: 'ER',
    openedAt: '2026-03-24T07:30:00Z',
  },
  {
    id: 'DSP-90385',
    customerId: '118822',
    customerName: 'Omar Farouk',
    customerInitials: 'OF',
    reason: 'Credit memo not applied',
    amountCents: 1_240_00,
    status: 'DENIED',
    priority: 'Low',
    assigneeName: 'James Chen',
    assigneeInitials: 'JC',
    openedAt: '2026-02-28T15:00:00Z',
  },
  {
    id: 'DSP-90380',
    customerId: '556677',
    customerName: 'Vertex Labs',
    customerInitials: 'VL',
    reason: 'Enterprise seat count dispute',
    amountCents: 18_500_00,
    status: 'IN REVIEW',
    priority: 'Critical',
    assigneeName: 'Priya Nair',
    assigneeInitials: 'PN',
    openedAt: '2026-03-27T18:00:00Z',
  },
  {
    id: 'DSP-90377',
    customerId: '334455',
    customerName: 'Helena Vogt',
    customerInitials: 'HV',
    reason: 'Return label fee dispute',
    amountCents: 45_99,
    status: 'RESOLVED',
    priority: 'Low',
    assigneeName: 'Elena Rodriguez',
    assigneeInitials: 'ER',
    openedAt: '2026-03-12T09:15:00Z',
  },
  {
    id: 'DSP-90374',
    customerId: '778899',
    customerName: 'Silverline Imports',
    customerInitials: 'SI',
    reason: 'Customs duty billing error',
    amountCents: 5_600_00,
    status: 'OPEN',
    priority: 'Medium',
    assigneeName: null,
    assigneeInitials: null,
    openedAt: '2026-03-19T14:50:00Z',
  },
  {
    id: 'DSP-90370',
    customerId: '661122',
    customerName: 'Renee Okonkwo',
    customerInitials: 'RO',
    reason: 'Partial refund missing tax',
    amountCents: 412_25,
    status: 'IN REVIEW',
    priority: 'High',
    assigneeName: 'James Chen',
    assigneeInitials: 'JC',
    openedAt: '2026-03-26T11:10:00Z',
  },
]

export const DISPUTE_TOTAL_COUNT = 1284
